name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install .
    - name: Test with Pytest
      run: pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
