name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
        os:
          - ubuntu-latest
          # - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Test with Pytest
      run: pytest

  lint:
    strategy:
      matrix:
        linter:
          - name: Flake8
            run: flake8 --config=setup.cfg tests
          - name: Black
            run: black --check tests
          - name: PyUpgrade
            run: pyupgrade --py36-plus `find tests -name "*.py"`
          - name: isort
            run: isort -c -v tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: ${{ matrix.linter.name }}
      run: ${{ matrix.linter.run }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install template dependecies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Build project docs
      run: |
        mkdir -p .cache/
        cd .cache/
        cookiecutter ../ --no-input --overwrite-if-exists project_name="My Package"
    - name: Generate project docs
      run: |
        cd .cache/my-package/docs
        pip install -r requirements.txt
        make html
